name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true # Condition
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: "Version and publish"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ ${{ github.base_ref }} = development ]; then
            npx lerna version prepatch --no-changelog --yes
          else
            npx lerna version prepatch --conventional-graduate --no-changelog --yes
          fi

          npx lerna publish from-git --yes
